// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Signature } from "./Signature";

export type DeviceState = { date_time: string, signature: Signature, rssi: number, };
