// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Snapshot } from "./Snapshot";

export type ServerMsg = { "type": "Heartbeat", "data": { seq: number, } } | { "type": "NewSnapshot", "data": { snapshot: Snapshot, } };
